name: Build and deploy Jekyll site to GitHub Pages

on:
  push

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
            
    # Standard usage
      - uses: helaili/jekyll-action@v2.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_src: './'
          target_branch: 'gh-pages'
          keep_history: false
          pre_build_commands: |
            echo "Installing additional dependencies..."
            gem install jekyll-postfiles -v 3.0

